name: FrontierMP build

on:
  push:
    branches:
      - final-rdr1-1.0.0
  pull_request:

jobs:
  windows-vs2022:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - name: Configure
        working-directory: FrontierMP-0.2.6-source
        run: cmake --preset windows-vs2022-x64 -DFRONTIER_BUILD_RDRMP_COMPAT=ON -DFRONTIER_CEF_PACKAGE_DIR=""
      - name: Build
        working-directory: FrontierMP-0.2.6-source
        run: cmake --build --preset windows-vs2022-x64-release --parallel --verbose
      - name: Test
        working-directory: FrontierMP-0.2.6-source
        run: ctest --test-dir build/vs2022-x64 -C Release --output-on-failure
